language: node_js
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@'>=2.13.5'
- npm install -g grunt-cli
after_script:
- node_modules/codeclimate-test-reporter/bin/codeclimate.js < build/lcov.info
before_deploy: grunt dist
deploy:
- provider: releases
  api_key:
    secure: OC1bB2i4KiY/JY91/+pmXZvz7q+6oAPgOyNXRyb4F/h+JqtljgRQnVvUFXyDLMSVfMJIaH+6+8Dv7SWM8fKV/KuGX7BArgd7Qu1JmLgwn7zpm7pDzHoVxKxAYIKprMFoWKngtgeosbb8ltWFMWOJGCebL872xeLzjDltXptupNlkxRTjTtPvCLgd8TbapfCehWZR5/co8hE4mCBcXCZ1ap0dcDY6soDHy8rV7tYFuwKnt79tJwnSrVAiysQvlK7jd3DQzpMekH9poY2tL2icsEFv/7YLVY40QSngKQ8MuSoG+O7KVsF6nc7S9WInpFgZ7bEuxXyj70r9Du8LoCzEV6j3mu3L3b2536qVIsd/E5l0hkuK9wTSkkQDpG73X9dgBg38er1senTuWEMkp/Zw4glc5a99oaoAF4TR4KHrPOim0OI7Gc//kYlPJUV/jXY/wq8xB/zaTLj4tovzMZ7wHTQCzCactqTLjrILUAh2eEwdFfRyIy7x22IBskHGawgZMD0mD2VTbFRh9i9VWsOHYAxiSUSaJeOGK/piG4U9niGoCEEOzTbVva316talj1jsGd/IUMIjpLAzCQdTtL8dZf8qqyRn30+dVi2uFCmtkHkIfOZ/lgW2Gh/oC3S3rvfvr9gps1VEQUguLR6Z+WHAA5ZGStpMUth171s7AQf6HZk=
  skip_cleanup: true
  file: html5-sortable.zip
  on:
    repo: clippings/html5-sortable
    tags: true
- provider: npm
  email: ikerin@gmail.com
  skip_cleanup: true
  api_key:
    secure: qv4djinToo2F4HF81FwZz9ShSwuggfQSlcIZS62Nyw10KNjYT5Nkbox+kHJWfXi9IFauFc+HkskhjJiVQrRypP5nKGmQSPHJGmEE1j71lKEKCc39P2tk6fiG20C/yLFnN/zPVfOE6s0iQ5JZqMCOsInpLQegSw197z4RNN1SW8upjethl+7FLXWnZRc35uEPUW2jB/CPVZ2kwpBZPS6RKCl16C2do4zZnUuqgGjYQoBKX6oXAiU4Q0FCaDednWV9CVQ5bNr5Rpj8Qi+rKB1tT3ffOCq+Vb9cLhX933pbCmDD9o4NKg1Adf7vc4z/nA340ElK+SphXbEwvKrrCbvIx2648zi5gjgoQBIhulZTWoA4Mqi8rMgIvvYdAlAqxeWXKnc9uQnP/LCe1Tz0ds6a8xrNuxz6scLN4S9W3/5R0hIc7GKxwFKTC9YbeQpdZ0vwx1KX1vHQ2o9n7t6r8/HX22+YOoE4N2wfOoObKIMLMT+vh5fIDdVcYqZ2lMaeiF4xZZurijuP9H/tZV5s54gSyPerZDB4EJhlV5dqFAmVZJ4f/RxkTKt/5/0bgJAmYsgcL4Xllbr6zkSynVlvUrodzmBBk1i6Ej33CqMVp+g4PMkrL3uckYpdByg2cqzcaRuco8CP6mTrOZ+SAOZQVabaVmEt5Bnlcw6cozj5wkmles4=
  on:
    repo: clippings/html5-sortable
    tags: true
